sql_name_map = {
	'solar' : {
		#################################
		# Weather measurements with SMA #
		#################################
		#'ExlSolIrr'	: ('Radiation (external)', 'W/m^2'), # always reads 0
		'IntSolIrr'	: ('Radiation', 'W/m^2'),
		'SMA-h-On'	: ('Total Hours On', ''),
		#'TmpAmb' : ('Ambient Temperature', ''), # seems broken.. -273 celcius consistently
		'TmpMdul'	: ('Outside Temperature', ''), #'TmpMdul C', 'TmpMdul F', 'TmpMdul K' <-- unit is encoded in name
		'WindVel'	: ('Wind Speed', ''),#'WindVel m/s' <-- unit is encoded in name
		####################
		# Solar panel info #
		####################
		'A.Ms.Amp'	: ('Unit A DC Current', 'A'),
		'A.Ms.Vol'	: ('Unit A DC Voltage', 'V'),
		'A.Ms.Watt'	: ('Unit A Watts', 'W'),
		'A1.Ms.Amp'	: ('Unit A1 DC Current', 'A'),
		'B.Ms.Amp'	: ('Unit B DC Current', 'A'),
		'B.Ms.Vol'	: ('Unit B DC Voltage', 'V'),
		'B.Ms.Watt'	: ('Unit B Watts', 'W'),
		'B1.Ms.Amp'	: ('Unit B1 DC Current', 'A'),
		'Error'	: ('Error', ''),
		'E-Total'	: ('Total Generated Energy', 'Wh'),
		'GM.TotS0Out'	: ('S0 Grid Feed-in Counter', ''),
		'GM.TotWhOut'	: ('Grid Feed-in Counter Reading', 'Wh'),
		'GridMs.A.phsA'	: ('Grid current phase L1', 'A'),
		'GridMs.A.phsB'	: ('Grid current phase L2', 'A'),
		'GridMs.A.phsC'	: ('Grid current phase L3', 'A'),
		'GridMs.Hz'	: ('Grid Frequency', 'Hz'),
		'GridMs.PhV.phsA'	: ('Grid voltage phase L1', 'V'),
		'GridMs.PhV.phsB'	: ('Grid voltage phase L2', 'V'),
		'GridMs.PhV.phsC'	: ('Grid voltage phase L3', 'V'),
		'GridMs.TotPF'	: ('Displacement power factor', ''),
		'GridMs.TotVA'	: ('Apparent power', 'VA'),
		'GridMs.TotVAr'	: ('Reactive power', 'VAr'),
		'GridMs.VA.phsA'	: ('Apparent power L1', 'VA'),
		'GridMs.VA.phsB'	: ('Apparent power L2', 'VA'),
		'GridMs.VA.phsC'	: ('Apparent power L3', 'VA'),
		'GridMs.VAr.phsA'	: ('Reactive power L1', 'VAr'),
		'GridMs.VAr.phsB'	: ('Reactive power L2', 'VAr'),
		'GridMs.VAr.phsC'	: ('Reactive power L3', 'VAr'),
		'GridMs.W.phsA'	: ('Power L1', 'W'),
		'GridMs.W.phsB'	: ('Power L2', 'W'),
		'GridMs.W.phsC'	: ('Power L3', 'W'),
		#'Inv.TmpLimStt'	: ('Derating', ''),
		'InvCtl.Stt'	: ('Status, device control', ''),
		'Iso.FltA'	: ('Residual current', ''),
		'Mode'	: ('Operating Mode', ''),
		'Mt.TotOpTmh'	: ('Feed-in time', 's'),
		'Mt.TotTmh'	: ('Operating time', 's'),
		#'Op.BckOpStt'	: ('', ''), # ???
		#'Op.EvtCntIstl'	: ('Number of events for installer', ''),
		#'Op.EvtCntUsr'	: ('Number of events for user', ''),
		#'Op.EvtNo'	: ('Current event number', ''),
		#'Op.EvtNoDvlp'	: ('', ''), # ???
		#'Op.GriSwCnt'	: ('Number of grid connections', ''),
		#'Op.GriSwStt'	: ('Grid relay/contactor', ''),
		'Op.Health'	: ('Condition', ''),
		#'Op.Prio'	: ('Recommended action', ''),
		#'Op.TmsRmg'	: ('Waiting time until feed-in', 's'),
		'Pac'	: ('Power', 'W'),
		'PCM-DigInStt'	: ('Status of digital inputs of power control module', ''),
		'PlntCtl.Stt'	: ('Status, PV system control', '')
	},

	'veris' : {
	'Time' : ('timestamp', 'veristime'),
	 'Channel #1' : ('Channel #1', 'A'),
	 'Channel #1 Max' : ('Channel #1 Max', 'A'),
	 'Channel #1 Demand' : ('Channel #1 Demand', 'A'),
	 'Channel #1 Energy' : ('Channel #1 Energy', 'kWh'),
	 'Channel #1 Power' : ('Channel #1 Power', 'kW'),
	 'Channel #1 Power Max' : ('Channel #1 Power Max', 'kW'),
	 'Channel #1 Power Demand' : ('Channel #1 Power Demand', 'kW'),
	 'Channel #1 Power Factor' : ('Channel #1 Power Factor', ''),
	 'Channel #2' : ('Channel #2', 'A'),
	 'Channel #2 Max' : ('Channel #2 Max', 'A'),
	 'Channel #2 Demand' : ('Channel #2 Demand', 'A'),
	 'Channel #2 Energy' : ('Channel #2 Energy', 'kWh'),
	 'Channel #2 Power' : ('Channel #2 Power', 'kW'),
	 'Channel #2 Power Max' : ('Channel #2 Power Max', 'kW'),
	 'Channel #2 Power Demand' : ('Channel #2 Power Demand', 'kW'),
	 'Channel #2 Power Factor' : ('Channel #2 Power Factor', ''),
	 'Channel #3' : ('Channel #3', 'A'),
	 'Channel #3 Max' : ('Channel #3 Max', 'A'),
	 'Channel #3 Demand' : ('Channel #3 Demand', 'A'),
	 'Channel #3 Energy' : ('Channel #3 Energy', 'kWh'),
	 'Channel #3 Power' : ('Channel #3 Power', 'kW'),
	 'Channel #3 Power Max' : ('Channel #3 Power Max', 'kW'),
	 'Channel #3 Power Demand' : ('Channel #3 Power Demand', 'kW'),
	 'Channel #3 Power Factor' : ('Channel #3 Power Factor', ''),
	 'Channel #4' : ('Channel #4', 'A'),
	 'Channel #4 Max' : ('Channel #4 Max', 'A'),
	 'Channel #4 Demand' : ('Channel #4 Demand', 'A'),
	 'Channel #4 Energy' : ('Channel #4 Energy', 'kWh'),
	 'Channel #4 Power' : ('Channel #4 Power', 'kW'),
	 'Channel #4 Power Max' : ('Channel #4 Power Max', 'kW'),
	 'Channel #4 Power Demand' : ('Channel #4 Power Demand', 'kW'),
	 'Channel #4 Power Factor' : ('Channel #4 Power Factor', ''),
	 'Channel #5' : ('Channel #5', 'A'),
	 'Channel #5 Max' : ('Channel #5 Max', 'A'),
	 'Channel #5 Demand' : ('Channel #5 Demand', 'A'),
	 'Channel #5 Energy' : ('Channel #5 Energy', 'kWh'),
	 'Channel #5 Power' : ('Channel #5 Power', 'kW'),
	 'Channel #5 Power Max' : ('Channel #5 Power Max', 'kW'),
	 'Channel #5 Power Demand' : ('Channel #5 Power Demand', 'kW'),
	 'Channel #5 Power Factor' : ('Channel #5 Power Factor', ''),
	 'Channel #6' : ('Channel #6', 'A'),
	 'Channel #6 Max' : ('Channel #6 Max', 'A'),
	 'Channel #6 Demand' : ('Channel #6 Demand', 'A'),
	 'Channel #6 Energy' : ('Channel #6 Energy', 'kWh'),
	 'Channel #6 Power' : ('Channel #6 Power', 'kW'),
	 'Channel #6 Power Max' : ('Channel #6 Power Max', 'kW'),
	 'Channel #6 Power Demand' : ('Channel #6 Power Demand', 'kW'),
	 'Channel #6 Power Factor' : ('Channel #6 Power Factor', ''),
	 'Channel #7' : ('Channel #7', 'A'),
	 'Channel #7 Max' : ('Channel #7 Max', 'A'),
	 'Channel #7 Demand' : ('Channel #7 Demand', 'A'),
	 'Channel #7 Energy' : ('Channel #7 Energy', 'kWh'),
	 'Channel #7 Power' : ('Channel #7 Power', 'kW'),
	 'Channel #7 Power Max' : ('Channel #7 Power Max', 'kW'),
	 'Channel #7 Power Demand' : ('Channel #7 Power Demand', 'kW'),
	 'Channel #7 Power Factor' : ('Channel #7 Power Factor', ''),
	 'Channel #8' : ('Channel #8', 'A'),
	 'Channel #8 Max' : ('Channel #8 Max', 'A'),
	 'Channel #8 Demand' : ('Channel #8 Demand', 'A'),
	 'Channel #8 Energy' : ('Channel #8 Energy', 'kWh'),
	 'Channel #8 Power' : ('Channel #8 Power', 'kW'),
	 'Channel #8 Power Max' : ('Channel #8 Power Max', 'kW'),
	 'Channel #8 Power Demand' : ('Channel #8 Power Demand', 'kW'),
	 'Channel #8 Power Factor' : ('Channel #8 Power Factor', ''),
	 'Channel #9' : ('Channel #9', 'A'),
	 'Channel #9 Max' : ('Channel #9 Max', 'A'),
	 'Channel #9 Demand' : ('Channel #9 Demand', 'A'),
	 'Channel #9 Energy' : ('Channel #9 Energy', 'kWh'),
	 'Channel #9 Power' : ('Channel #9 Power', 'kW'),
	 'Channel #9 Power Max' : ('Channel #9 Power Max', 'kW'),
	 'Channel #9 Power Demand' : ('Channel #9 Power Demand', 'kW'),
	 'Channel #9 Power Factor' : ('Channel #9 Power Factor', ''),
	 'Channel #10' : ('Channel #10', 'A'),
	 'Channel #10 Max' : ('Channel #10 Max', 'A'),
	 'Channel #10 Demand' : ('Channel #10 Demand', 'A'),
	 'Channel #10 Energy' : ('Channel #10 Energy', 'kWh'),
	 'Channel #10 Power' : ('Channel #10 Power', 'kW'),
	 'Channel #10 Power Max' : ('Channel #10 Power Max', 'kW'),
	 'Channel #10 Power Demand' : ('Channel #10 Power Demand', 'kW'),
	 'Channel #10 Power Factor' : ('Channel #10 Power Factor', ''),
	 'Channel #11' : ('Channel #11', 'A'),
	 'Channel #11 Max' : ('Channel #11 Max', 'A'),
	 'Channel #11 Demand' : ('Channel #11 Demand', 'A'),
	 'Channel #11 Energy' : ('Channel #11 Energy', 'kWh'),
	 'Channel #11 Power' : ('Channel #11 Power', 'kW'),
	 'Channel #11 Power Max' : ('Channel #11 Power Max', 'kW'),
	 'Channel #11 Power Demand' : ('Channel #11 Power Demand', 'kW'),
	 'Channel #11 Power Factor' : ('Channel #11 Power Factor', ''),
	 'Channel #12' : ('Channel #12', 'A'),
	 'Channel #12 Max' : ('Channel #12 Max', 'A'),
	 'Channel #12 Demand' : ('Channel #12 Demand', 'A'),
	 'Channel #12 Energy' : ('Channel #12 Energy', 'kWh'),
	 'Channel #12 Power' : ('Channel #12 Power', 'kW'),
	 'Channel #12 Power Max' : ('Channel #12 Power Max', 'kW'),
	 'Channel #12 Power Demand' : ('Channel #12 Power Demand', 'kW'),
	 'Channel #12 Power Factor' : ('Channel #12 Power Factor', ''),
	 'Channel #13' : ('Channel #13', 'A'),
	 'Channel #13 Max' : ('Channel #13 Max', 'A'),
	 'Channel #13 Demand' : ('Channel #13 Demand', 'A'),
	 'Channel #13 Energy' : ('Channel #13 Energy', 'kWh'),
	 'Channel #13 Power' : ('Channel #13 Power', 'kW'),
	 'Channel #13 Power Max' : ('Channel #13 Power Max', 'kW'),
	 'Channel #13 Power Demand' : ('Channel #13 Power Demand', 'kW'),
	 'Channel #13 Power Factor' : ('Channel #13 Power Factor', ''),
	 'Channel #14' : ('Channel #14', 'A'),
	 'Channel #14 Max' : ('Channel #14 Max', 'A'),
	 'Channel #14 Demand' : ('Channel #14 Demand', 'A'),
	 'Channel #14 Energy' : ('Channel #14 Energy', 'kWh'),
	 'Channel #14 Power' : ('Channel #14 Power', 'kW'),
	 'Channel #14 Power Max' : ('Channel #14 Power Max', 'kW'),
	 'Channel #14 Power Demand' : ('Channel #14 Power Demand', 'kW'),
	 'Channel #14 Power Factor' : ('Channel #14 Power Factor', ''),
	 'Channel #15' : ('Channel #15', 'A'),
	 'Channel #15 Max' : ('Channel #15 Max', 'A'),
	 'Channel #15 Demand' : ('Channel #15 Demand', 'A'),
	 'Channel #15 Energy' : ('Channel #15 Energy', 'kWh'),
	 'Channel #15 Power' : ('Channel #15 Power', 'kW'),
	 'Channel #15 Power Max' : ('Channel #15 Power Max', 'kW'),
	 'Channel #15 Power Demand' : ('Channel #15 Power Demand', 'kW'),
	 'Channel #15 Power Factor' : ('Channel #15 Power Factor', ''),
	 'Channel #16' : ('Channel #16', 'A'),
	 'Channel #16 Max' : ('Channel #16 Max', 'A'),
	 'Channel #16 Demand' : ('Channel #16 Demand', 'A'),
	 'Channel #16 Energy' : ('Channel #16 Energy', 'kWh'),
	 'Channel #16 Power' : ('Channel #16 Power', 'kW'),
	 'Channel #16 Power Max' : ('Channel #16 Power Max', 'kW'),
	 'Channel #16 Power Demand' : ('Channel #16 Power Demand', 'kW'),
	 'Channel #16 Power Factor' : ('Channel #16 Power Factor', ''),
	 'Channel #17' : ('Channel #17', 'A'),
	 'Channel #17 Max' : ('Channel #17 Max', 'A'),
	 'Channel #17 Demand' : ('Channel #17 Demand', 'A'),
	 'Channel #17 Energy' : ('Channel #17 Energy', 'kWh'),
	 'Channel #17 Power' : ('Channel #17 Power', 'kW'),
	 'Channel #17 Power Max' : ('Channel #17 Power Max', 'kW'),
	 'Channel #17 Power Demand' : ('Channel #17 Power Demand', 'kW'),
	 'Channel #17 Power Factor' : ('Channel #17 Power Factor', ''),
	 'Channel #18' : ('Channel #18', 'A'),
	 'Channel #18 Max' : ('Channel #18 Max', 'A'),
	 'Channel #18 Demand' : ('Channel #18 Demand', 'A'),
	 'Channel #18 Energy' : ('Channel #18 Energy', 'kWh'),
	 'Channel #18 Power' : ('Channel #18 Power', 'kW'),
	 'Channel #18 Power Max' : ('Channel #18 Power Max', 'kW'),
	 'Channel #18 Power Demand' : ('Channel #18 Power Demand', 'kW'),
	 'Channel #18 Power Factor' : ('Channel #18 Power Factor', ''),
	 'Channel #19' : ('Channel #19', 'A'),
	 'Channel #19 Max' : ('Channel #19 Max', 'A'),
	 'Channel #19 Demand' : ('Channel #19 Demand', 'A'),
	 'Channel #19 Energy' : ('Channel #19 Energy', 'kWh'),
	 'Channel #19 Power' : ('Channel #19 Power', 'kW'),
	 'Channel #19 Power Max' : ('Channel #19 Power Max', 'kW'),
	 'Channel #19 Power Demand' : ('Channel #19 Power Demand', 'kW'),
	 'Channel #19 Power Factor' : ('Channel #19 Power Factor', ''),
	 'Channel #20' : ('Channel #20', 'A'),
	 'Channel #20 Max' : ('Channel #20 Max', 'A'),
	 'Channel #20 Demand' : ('Channel #20 Demand', 'A'),
	 'Channel #20 Energy' : ('Channel #20 Energy', 'kWh'),
	 'Channel #20 Power' : ('Channel #20 Power', 'kW'),
	 'Channel #20 Power Max' : ('Channel #20 Power Max', 'kW'),
	 'Channel #20 Power Demand' : ('Channel #20 Power Demand', 'kW'),
	 'Channel #20 Power Factor' : ('Channel #20 Power Factor', ''),
	 'Channel #21' : ('Channel #21', 'A'),
	 'Channel #21 Max' : ('Channel #21 Max', 'A'),
	 'Channel #21 Demand' : ('Channel #21 Demand', 'A'),
	 'Channel #21 Energy' : ('Channel #21 Energy', 'kWh'),
	 'Channel #21 Power' : ('Channel #21 Power', 'kW'),
	 'Channel #21 Power Max' : ('Channel #21 Power Max', 'kW'),
	 'Channel #21 Power Demand' : ('Channel #21 Power Demand', 'kW'),
	 'Channel #21 Power Factor' : ('Channel #21 Power Factor', ''),
	 'Channel #22' : ('Channel #22', 'A'),
	 'Channel #22 Max' : ('Channel #22 Max', 'A'),
	 'Channel #22 Demand' : ('Channel #22 Demand', 'A'),
	 'Channel #22 Energy' : ('Channel #22 Energy', 'kWh'),
	 'Channel #22 Power' : ('Channel #22 Power', 'kW'),
	 'Channel #22 Power Max' : ('Channel #22 Power Max', 'kW'),
	 'Channel #22 Power Demand' : ('Channel #22 Power Demand', 'kW'),
	 'Channel #22 Power Factor' : ('Channel #22 Power Factor', ''),
	 'Channel #23' : ('Channel #23', 'A'),
	 'Channel #23 Max' : ('Channel #23 Max', 'A'),
	 'Channel #23 Demand' : ('Channel #23 Demand', 'A'),
	 'Channel #23 Energy' : ('Channel #23 Energy', 'kWh'),
	 'Channel #23 Power' : ('Channel #23 Power', 'kW'),
	 'Channel #23 Power Max' : ('Channel #23 Power Max', 'kW'),
	 'Channel #23 Power Demand' : ('Channel #23 Power Demand', 'kW'),
	 'Channel #23 Power Factor' : ('Channel #23 Power Factor', ''),
	 'Channel #24' : ('Channel #24', 'A'),
	 'Channel #24 Max' : ('Channel #24 Max', 'A'),
	 'Channel #24 Demand' : ('Channel #24 Demand', 'A'),
	 'Channel #24 Energy' : ('Channel #24 Energy', 'kWh'),
	 'Channel #24 Power' : ('Channel #24 Power', 'kW'),
	 'Channel #24 Power Max' : ('Channel #24 Power Max', 'kW'),
	 'Channel #24 Power Demand' : ('Channel #24 Power Demand', 'kW'),
	 'Channel #24 Power Factor' : ('Channel #24 Power Factor', ''),
	 'Channel #25' : ('Channel #25', 'A'),
	 'Channel #25 Max' : ('Channel #25 Max', 'A'),
	 'Channel #25 Demand' : ('Channel #25 Demand', 'A'),
	 'Channel #25 Energy' : ('Channel #25 Energy', 'kWh'),
	 'Channel #25 Power' : ('Channel #25 Power', 'kW'),
	 'Channel #25 Power Max' : ('Channel #25 Power Max', 'kW'),
	 'Channel #25 Power Demand' : ('Channel #25 Power Demand', 'kW'),
	 'Channel #25 Power Factor' : ('Channel #25 Power Factor', ''),
	 'Channel #26' : ('Channel #26', 'A'),
	 'Channel #26 Max' : ('Channel #26 Max', 'A'),
	 'Channel #26 Demand' : ('Channel #26 Demand', 'A'),
	 'Channel #26 Energy' : ('Channel #26 Energy', 'kWh'),
	 'Channel #26 Power' : ('Channel #26 Power', 'kW'),
	 'Channel #26 Power Max' : ('Channel #26 Power Max', 'kW'),
	 'Channel #26 Power Demand' : ('Channel #26 Power Demand', 'kW'),
	 'Channel #26 Power Factor' : ('Channel #26 Power Factor', ''),
	 'Channel #27' : ('Channel #27', 'A'),
	 'Channel #27 Max' : ('Channel #27 Max', 'A'),
	 'Channel #27 Demand' : ('Channel #27 Demand', 'A'),
	 'Channel #27 Energy' : ('Channel #27 Energy', 'kWh'),
	 'Channel #27 Power' : ('Channel #27 Power', 'kW'),
	 'Channel #27 Power Max' : ('Channel #27 Power Max', 'kW'),
	 'Channel #27 Power Demand' : ('Channel #27 Power Demand', 'kW'),
	 'Channel #27 Power Factor' : ('Channel #27 Power Factor', ''),
	 'Channel #28' : ('Channel #28', 'A'),
	 'Channel #28 Max' : ('Channel #28 Max', 'A'),
	 'Channel #28 Demand' : ('Channel #28 Demand', 'A'),
	 'Channel #28 Energy' : ('Channel #28 Energy', 'kWh'),
	 'Channel #28 Power' : ('Channel #28 Power', 'kW'),
	 'Channel #28 Power Max' : ('Channel #28 Power Max', 'kW'),
	 'Channel #28 Power Demand' : ('Channel #28 Power Demand', 'kW'),
	 'Channel #28 Power Factor' : ('Channel #28 Power Factor', ''),
	 'Channel #29' : ('Channel #29', 'A'),
	 'Channel #29 Max' : ('Channel #29 Max', 'A'),
	 'Channel #29 Demand' : ('Channel #29 Demand', 'A'),
	 'Channel #29 Energy' : ('Channel #29 Energy', 'kWh'),
	 'Channel #29 Power' : ('Channel #29 Power', 'kW'),
	 'Channel #29 Power Max' : ('Channel #29 Power Max', 'kW'),
	 'Channel #29 Power Demand' : ('Channel #29 Power Demand', 'kW'),
	 'Channel #29 Power Factor' : ('Channel #29 Power Factor', ''),
	 'Channel #30' : ('Channel #30', 'A'),
	 'Channel #30 Max' : ('Channel #30 Max', 'A'),
	 'Channel #30 Demand' : ('Channel #30 Demand', 'A'),
	 'Channel #30 Energy' : ('Channel #30 Energy', 'kWh'),
	 'Channel #30 Power' : ('Channel #30 Power', 'kW'),
	 'Channel #30 Power Max' : ('Channel #30 Power Max', 'kW'),
	 'Channel #30 Power Demand' : ('Channel #30 Power Demand', 'kW'),
	 'Channel #30 Power Factor' : ('Channel #30 Power Factor', ''),
	 'Channel #31' : ('Channel #31', 'A'),
	 'Channel #31 Max' : ('Channel #31 Max', 'A'),
	 'Channel #31 Demand' : ('Channel #31 Demand', 'A'),
	 'Channel #31 Energy' : ('Channel #31 Energy', 'kWh'),
	 'Channel #31 Power' : ('Channel #31 Power', 'kW'),
	 'Channel #31 Power Max' : ('Channel #31 Power Max', 'kW'),
	 'Channel #31 Power Demand' : ('Channel #31 Power Demand', 'kW'),
	 'Channel #31 Power Factor' : ('Channel #31 Power Factor', ''),
	 'Channel #32' : ('Channel #32', 'A'),
	 'Channel #32 Max' : ('Channel #32 Max', 'A'),
	 'Channel #32 Demand' : ('Channel #32 Demand', 'A'),
	 'Channel #32 Energy' : ('Channel #32 Energy', 'kWh'),
	 'Channel #32 Power' : ('Channel #32 Power', 'kW'),
	 'Channel #32 Power Max' : ('Channel #32 Power Max', 'kW'),
	 'Channel #32 Power Demand' : ('Channel #32 Power Demand', 'kW'),
	 'Channel #32 Power Factor' : ('Channel #32 Power Factor', ''),
	 'Channel #33' : ('Channel #33', 'A'),
	 'Channel #33 Max' : ('Channel #33 Max', 'A'),
	 'Channel #33 Demand' : ('Channel #33 Demand', 'A'),
	 'Channel #33 Energy' : ('Channel #33 Energy', 'kWh'),
	 'Channel #33 Power' : ('Channel #33 Power', 'kW'),
	 'Channel #33 Power Max' : ('Channel #33 Power Max', 'kW'),
	 'Channel #33 Power Demand' : ('Channel #33 Power Demand', 'kW'),
	 'Channel #33 Power Factor' : ('Channel #33 Power Factor', ''),
	 'Channel #34' : ('Channel #34', 'A'),
	 'Channel #34 Max' : ('Channel #34 Max', 'A'),
	 'Channel #34 Demand' : ('Channel #34 Demand', 'A'),
	 'Channel #34 Energy' : ('Channel #34 Energy', 'kWh'),
	 'Channel #34 Power' : ('Channel #34 Power', 'kW'),
	 'Channel #34 Power Max' : ('Channel #34 Power Max', 'kW'),
	 'Channel #34 Power Demand' : ('Channel #34 Power Demand', 'kW'),
	 'Channel #34 Power Factor' : ('Channel #34 Power Factor', ''),
	 'Channel #35' : ('Channel #35', 'A'),
	 'Channel #35 Max' : ('Channel #35 Max', 'A'),
	 'Channel #35 Demand' : ('Channel #35 Demand', 'A'),
	 'Channel #35 Energy' : ('Channel #35 Energy', 'kWh'),
	 'Channel #35 Power' : ('Channel #35 Power', 'kW'),
	 'Channel #35 Power Max' : ('Channel #35 Power Max', 'kW'),
	 'Channel #35 Power Demand' : ('Channel #35 Power Demand', 'kW'),
	 'Channel #35 Power Factor' : ('Channel #35 Power Factor', ''),
	 'Channel #36' : ('Channel #36', 'A'),
	 'Channel #36 Max' : ('Channel #36 Max', 'A'),
	 'Channel #36 Demand' : ('Channel #36 Demand', 'A'),
	 'Channel #36 Energy' : ('Channel #36 Energy', 'kWh'),
	 'Channel #36 Power' : ('Channel #36 Power', 'kW'),
	 'Channel #36 Power Max' : ('Channel #36 Power Max', 'kW'),
	 'Channel #36 Power Demand' : ('Channel #36 Power Demand', 'kW'),
	 'Channel #36 Power Factor' : ('Channel #36 Power Factor', ''),
	 'Channel #37' : ('Channel #37', 'A'),
	 'Channel #37 Max' : ('Channel #37 Max', 'A'),
	 'Channel #37 Demand' : ('Channel #37 Demand', 'A'),
	 'Channel #37 Energy' : ('Channel #37 Energy', 'kWh'),
	 'Channel #37 Power' : ('Channel #37 Power', 'kW'),
	 'Channel #37 Power Max' : ('Channel #37 Power Max', 'kW'),
	 'Channel #37 Power Demand' : ('Channel #37 Power Demand', 'kW'),
	 'Channel #37 Power Factor' : ('Channel #37 Power Factor', ''),
	 'Channel #38' : ('Channel #38', 'A'),
	 'Channel #38 Max' : ('Channel #38 Max', 'A'),
	 'Channel #38 Demand' : ('Channel #38 Demand', 'A'),
	 'Channel #38 Energy' : ('Channel #38 Energy', 'kWh'),
	 'Channel #38 Power' : ('Channel #38 Power', 'kW'),
	 'Channel #38 Power Max' : ('Channel #38 Power Max', 'kW'),
	 'Channel #38 Power Demand' : ('Channel #38 Power Demand', 'kW'),
	 'Channel #38 Power Factor' : ('Channel #38 Power Factor', ''),
	 'Channel #39' : ('Channel #39', 'A'),
	 'Channel #39 Max' : ('Channel #39 Max', 'A'),
	 'Channel #39 Demand' : ('Channel #39 Demand', 'A'),
	 'Channel #39 Energy' : ('Channel #39 Energy', 'kWh'),
	 'Channel #39 Power' : ('Channel #39 Power', 'kW'),
	 'Channel #39 Power Max' : ('Channel #39 Power Max', 'kW'),
	 'Channel #39 Power Demand' : ('Channel #39 Power Demand', 'kW'),
	 'Channel #39 Power Factor' : ('Channel #39 Power Factor', ''),
	 'Channel #40' : ('Channel #40', 'A'),
	 'Channel #40 Max' : ('Channel #40 Max', 'A'),
	 'Channel #40 Demand' : ('Channel #40 Demand', 'A'),
	 'Channel #40 Energy' : ('Channel #40 Energy', 'kWh'),
	 'Channel #40 Power' : ('Channel #40 Power', 'kW'),
	 'Channel #40 Power Max' : ('Channel #40 Power Max', 'kW'),
	 'Channel #40 Power Demand' : ('Channel #40 Power Demand', 'kW'),
	 'Channel #40 Power Factor' : ('Channel #40 Power Factor', ''),
	 'Channel #41' : ('Channel #41', 'A'),
	 'Channel #41 Max' : ('Channel #41 Max', 'A'),
	 'Channel #41 Demand' : ('Channel #41 Demand', 'A'),
	 'Channel #41 Energy' : ('Channel #41 Energy', 'kWh'),
	 'Channel #41 Power' : ('Channel #41 Power', 'kW'),
	 'Channel #41 Power Max' : ('Channel #41 Power Max', 'kW'),
	 'Channel #41 Power Demand' : ('Channel #41 Power Demand', 'kW'),
	 'Channel #41 Power Factor' : ('Channel #41 Power Factor', ''),
	 'Channel #42' : ('Channel #42', 'A'),
	 'Channel #42 Max' : ('Channel #42 Max', 'A'),
	 'Channel #42 Demand' : ('Channel #42 Demand', 'A'),
	 'Channel #42 Energy' : ('Channel #42 Energy', 'kWh'),
	 'Channel #42 Power' : ('Channel #42 Power', 'kW'),
	 'Channel #42 Power Max' : ('Channel #42 Power Max', 'kW'),
	 'Channel #42 Power Demand' : ('Channel #42 Power Demand', 'kW'),
	 'Channel #42 Power Factor' : ('Channel #42 Power Factor', ''),
	 'Frequency' : ('Frequency', 'Hz'),
	 'Volts L-N 3ph Ave' : ('Volts L-N 3ph Average', 'V'),
	 'Volts L-L 3ph Ave' : ('Volts L-L 3ph Average', 'V'),
	 'Volts A-N' : ('Volts A-N', 'V'),
	 'Volts B-N' : ('Volts B-N', 'V'),
	 'Volts C-N' : ('Volts C-N', 'V'),
	 'Volts A-B' : ('Volts A-B', 'V'),
	 'Volts B-C' : ('Volts B-C', 'V'),
	 'Volts C-A' : ('Volts C-A', 'V'),
	 '3ph kWh' : ('3ph kWh', 'kWh'),
	 '3ph Total kW' : ('3ph Total kW', 'kW'),
	 '3ph Total PF' : ('3ph Total PF', ''),
	 '3ph Ave Current' : ('3ph Ave Current', 'A'),
	 'kW Phase 1' : ('kW Phase 1', 'kW'),
	 'kW Phase 2' : ('kW Phase 2', 'kW'),
	 'kW Phase 3' : ('kW Phase 3', 'kW'),
	 'PF Phase 1' : ('PF Phase 1', ''),
	 'PF Phase 2' : ('PF Phase 2', ''),
	 'PF Phase 3' : ('PF Phase 3', ''),
	 'Current Phase 1' : ('Current Phase 1', 'A'),
	 'Current Phase 2' : ('Current Phase 2', 'A'),
	 'Current Phase 3' : ('Current Phase 3', 'A'),
	 'Current Phase 4' : ('Current Phase 4', 'A'),
	 'Current Demand Phase 1' : ('Current Demand Phase 1', 'A'),
	 'Current Demand Phase 2' : ('Current Demand Phase 2', 'A'),
	 'Current Demand Phase 3' : ('Current Demand Phase 3', 'A'),
	 'Current Demand Phase 4' : ('Current Demand Phase 4', 'A'),
	 'Max Current Demand Phase 1' : ('Max Current Demand Phase 1', 'A'),
	 'Max Current Demand Phase 2' : ('Max Current Demand Phase 2', 'A'),
	 'Max Current Demand Phase 3' : ('Max Current Demand Phase 3', 'A'),
	 'Max Current Demand Phase 4' : ('Max Current Demand Phase 4', 'A'),
	 '3ph Present KW Total Demand' : ('3ph Present KW Total Demand', 'kW'),
	 '3ph Max KW Total Demand' : ('3ph Max KW Total Demand', 'kW'),
	 'Max Current Phase 1' : ('Max Current Phase 1', 'A'),
	 'Max Current Phase 2' : ('Max Current Phase 2', 'A'),
	 'Max Current Phase 3' : ('Max Current Phase 3', 'A'),
	 'Max Current Phase 4' : ('Max Current Phase 4', 'A'),
	 '3ph Max KW Total' : ('3ph Max KW Total', 'kW')
	 },

	'hvac' : {
		
	},

	'weather' : {

	}
}